#!/bin/bash
#$ -N MIDAS_species.bash
#$ -cwd # Run qsub script from desired working directory
#$ -V
#$ -e /u/home/j/jonmah/postproc_error
#$ -o /u/home/j/jonmah/postproc_output
#$ -l h_data=25G
#$ -l h_rt=00:30:00

# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_1_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/1_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_2_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/2_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_3_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/3_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_4_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/4_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_5_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/5_

# /u/project/ngarud/Garud_lab/UHGG

# Akkermansia muciniphila B
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/10
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_11_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/11
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_12_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/12
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/13
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Akkermansia_muciniphila_B/GUT_GENOME143202_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Akkermansia_muciniphila_B ../Data/UHGG/UHGG_Akkermansia_muciniphila_B/15

# Alistipes finegoldii
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/10
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/15
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/16
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_17_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/17
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_18_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/18

# Alistipes onderdonkii
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_onderdonkii/GUT_GENOME000285_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_onderdonkii ../Data/UHGG/UHGG_Alistipes_onderdonkii/7

# Alistipes putredinis
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_putredinis/GUT_GENOME095971_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_putredinis ../Data/UHGG/UHGG_Alistipes_putredinis/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_putredinis/GUT_GENOME095971_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_putredinis ../Data/UHGG/UHGG_Alistipes_putredinis/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_putredinis/GUT_GENOME095971_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_putredinis ../Data/UHGG/UHGG_Alistipes_putredinis/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_putredinis/GUT_GENOME095971_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_putredinis ../Data/UHGG/UHGG_Alistipes_putredinis/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_putredinis/GUT_GENOME095971_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_putredinis ../Data/UHGG/UHGG_Alistipes_putredinis/5

# Alistipes shahii
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_12_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/12
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/13
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/15
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/16
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_17_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/17
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_shahii/GUT_GENOME000008_18_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Alistipes_shahii ../Data/UHGG/UHGG_Alistipes_shahii/18

# Bacteroides fragilis
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/5

# Bacteroides ovatus
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/10
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_11_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/11
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_12_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/12
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/13
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/15
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/16
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_17_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/17
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_18_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/18
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_19_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/19
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_20_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/20
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_21_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/21
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_22_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/22
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_23_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/23
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_24_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/24
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_ovatus/GUT_GENOME096203_25_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_ovatus ../Data/UHGG/UHGG_Bacteroides_ovatus/25

# Bacteroides stercoris
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_19_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/19
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_29_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/29
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_39_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/39
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_53_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/53
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_54_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/54
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_55_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/55
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_56_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/56
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_57_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/57
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_58_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/58
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_59_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/59
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_60_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/60
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_62_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/62
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_63_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/63
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_64_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/64
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_66_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/66
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_67_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/67
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_68_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/68
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_69_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/69
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_70_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/70
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_71_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/71
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_72_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/72
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_73_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/73
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_74_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/74
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_75_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/75

# Bacteroides thetaiotaomicron
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_38_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/38
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_39_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/39
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_43_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/43
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_44_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/44
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_45_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/45
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_46_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/46
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_47_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/47
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_48_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/48
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_49_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/49
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_50_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/50
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_51_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/51
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_52_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/52
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_53_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/53
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_54_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/54
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_55_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/55
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_56_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/56
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_thetaiotaomicron/GUT_GENOME001120_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_thetaiotaomicron ../Data/UHGG/UHGG_Bacteroides_thetaiotaomicron/9

# Bacteroides uniformis
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_uniformis/GUT_GENOME096083_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_uniformis ../Data/UHGG/UHGG_Bacteroides_uniformis/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_uniformis/GUT_GENOME096083_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_uniformis ../Data/UHGG/UHGG_Bacteroides_uniformis/15

# Bacteroides xylanisolvens
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/10
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_11_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/11
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_12_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/12
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/13
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_xylanisolvens/GUT_GENOME096080_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_xylanisolvens ../Data/UHGG/UHGG_Bacteroides_xylanisolvens/15

# Barnesiella intestinihominis
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Barnesiella_intestinihominis/GUT_GENOME000682_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Barnesiella_intestinihominis ../Data/UHGG/UHGG_Barnesiella_intestinihominis/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Barnesiella_intestinihominis/GUT_GENOME000682_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Barnesiella_intestinihominis ../Data/UHGG/UHGG_Barnesiella_intestinihominis/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Barnesiella_intestinihominis/GUT_GENOME000682_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Barnesiella_intestinihominis ../Data/UHGG/UHGG_Barnesiella_intestinihominis/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Barnesiella_intestinihominis/GUT_GENOME000682_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Barnesiella_intestinihominis ../Data/UHGG/UHGG_Barnesiella_intestinihominis/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Barnesiella_intestinihominis/GUT_GENOME000682_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Barnesiella_intestinihominis ../Data/UHGG/UHGG_Barnesiella_intestinihominis/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Barnesiella_intestinihominis/GUT_GENOME000682_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Barnesiella_intestinihominis ../Data/UHGG/UHGG_Barnesiella_intestinihominis/6

# Dialister invisus
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/10
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_11_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/11
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_12_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/12
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/13
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/15
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/16
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_17_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/17
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_18_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/18
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_23_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/23
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Dialister_invisus/GUT_GENOME258044_24_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Dialister_invisus ../Data/UHGG/UHGG_Dialister_invisus/24

# Odoribacter splanchnicus
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_29_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/29
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_30_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/30
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_31_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/31
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_32_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/32
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_33_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/33
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_34_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/34
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_35_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/35
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_36_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/36
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Odoribacter_splanchnicus/GUT_GENOME001635_37_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Odoribacter_splanchnicus ../Data/UHGG/UHGG_Odoribacter_splanchnicus/37

# Parabacteroides distasonis
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_distasonis/GUT_GENOME001635_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_distasonis ../Data/UHGG/UHGG_Parabacteroides_distasonis/1

# Parabacteroides merdae
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/14
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/15
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/16
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_17_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/17
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_18_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/18
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Parabacteroides_merdae/GUT_GENOME000192_19_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Parabacteroides_merdae ../Data/UHGG/UHGG_Parabacteroides_merdae/19

# Ruminococcus_E_bromii_B
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Ruminococcus_E_bromii_B/GUT_GENOME001659_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Ruminococcus_E_bromii_B ../Data/UHGG/UHGG_Ruminococcus_E_bromii_B/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Ruminococcus_E_bromii_B/GUT_GENOME001659_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Ruminococcus_E_bromii_B ../Data/UHGG/UHGG_Ruminococcus_E_bromii_B/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Ruminococcus_E_bromii_B/GUT_GENOME001659_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Ruminococcus_E_bromii_B ../Data/UHGG/UHGG_Ruminococcus_E_bromii_B/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Ruminococcus_E_bromii_B/GUT_GENOME001659_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Ruminococcus_E_bromii_B ../Data/UHGG/UHGG_Ruminococcus_E_bromii_B/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Ruminococcus_E_bromii_B/GUT_GENOME001659_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Ruminococcus_E_bromii_B ../Data/UHGG/UHGG_Ruminococcus_E_bromii_B/5

# Prevotella copri
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_59_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/59
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_68_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/68
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_69_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/69
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_78_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/78
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_79_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/79
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_85_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/85
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_86_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/86
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_87_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/87
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_88_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/88
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_89_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/89
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_90_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/90
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_91_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/91
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_92_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/92
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_93_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/93
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_94_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/94
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_95_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/95
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_96_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/96
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_97_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/97
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_98_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/98
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_99_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/99

# Bacteroides_A_coprocola
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/2
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/3
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/4
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/5
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/6
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/7
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/8
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/9
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/10
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_11_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/11
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_12_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/12
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/13
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/14
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/15
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/16
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_17_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/17
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_18_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/18
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_19_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/19

# Faecalibacterium prausnitzii K
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/9

# Bacteroides_eggerthii
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_1_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/1
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_2_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/2
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_3_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/3
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_4_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/4
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_5_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/5
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_6_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/6
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_7_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/7
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_8_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/8
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_9_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/9
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_10_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/10
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_11_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/11
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_13_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/13
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_14_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/14
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_15_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/15
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_16_haplotypes.csv ../Data/UHGG/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/16
