#!/bin/bash
#$ -N MIDAS_species.bash
#$ -cwd # Run qsub script from desired working directory
#$ -V
#$ -e /u/home/j/jonmah/postproc_error
#$ -o /u/home/j/jonmah/postproc_output
#$ -l h_data=25G
#$ -l h_rt=00:30:00

# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_1_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/1_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_2_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/2_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_3_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/3_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_4_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/4_
# python parse_haplotype_catalog.py ../Data/UHGG/UHGG_Bacteroides_fragilis/GUT_GENOME096063_5_haplotypes.csv ../Data/UHGG/UHGG_Bacteroides_fragilis/5_

# /u/project/ngarud/Garud_lab/UHGG

# B. fragilis
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_1_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_fragilis/GUT_GENOME096063_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_fragilis ../Data/UHGG/UHGG_Bacteroides_fragilis/5

# A. finegoldii
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_1_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_6_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_7_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_8_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_9_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_10_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/10
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_15_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/15
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_16_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/16
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_17_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/17
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Alistipes_finegoldii/GUT_GENOME111543_18_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Alistipes_finegoldii ../Data/UHGG/UHGG_Alistipes_finegoldii/18

# Bacteroides_stercoris
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_1_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_6_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_7_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_8_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_9_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_19_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/19
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_29_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/29
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_39_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/39
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_53_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/53
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_54_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/54
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_55_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/55
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_56_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/56
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_57_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/57
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_58_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/58
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_59_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/59
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_60_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/60
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_62_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/62
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_63_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/63
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_64_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/64
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_66_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/66
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_67_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/67
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_68_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/68
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_69_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/69
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_70_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/70
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_71_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/71
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_72_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/72
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_73_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/73
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_74_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/74
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_stercoris/GUT_GENOME239662_75_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_stercoris ../Data/UHGG/UHGG_Bacteroides_stercoris/75

# Prevotella_copri
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_1_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_6_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_7_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_8_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_9_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/9
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_59_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/59
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_68_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/68
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_69_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/69
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_78_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/78
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_79_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/79
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_85_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/85
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_86_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/86
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_87_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/87
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_88_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/88
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_89_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/89
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_90_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/90
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_91_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/91
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_92_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/92
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_93_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/93
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_94_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/94
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_95_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/95
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_96_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/96
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_97_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/97
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_98_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/98
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Prevotella_copri/GUT_GENOME140299_99_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Prevotella_copri ../Data/UHGG/UHGG_Prevotella_copri/99

# Bacteroides_A_coprocola
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/2
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/3
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/4
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/5
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_6_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/6
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_7_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/7
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_8_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/8
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_9_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/9
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_10_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/10
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_11_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/11
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_12_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/12
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_13_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/13
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_14_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/14
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_15_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/15
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_16_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/16
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_17_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/17
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_18_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/18
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_A_coprocola/GUT_GENOME095979_19_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_A_coprocola ../Data/UHGG/UHGG_Bacteroides_A_coprocola/19

# Faecalibacterium_prausnitzii_K
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_1_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/1
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/2
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/3
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/4
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/5
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_6_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/6
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_7_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/7
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_8_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/8
python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Faecalibacterium_prausnitzii_K/GUT_GENOME095967_9_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Faecalibacterium_prausnitzii_K ../Data/UHGG/UHGG_Faecalibacterium_prausnitzii_K/9

# Bacteroides_eggerthii
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_1_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/1
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_2_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/2
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_3_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/3
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_4_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/4
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_5_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/5
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_6_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/6
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_7_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/7
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_8_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/8
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_9_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/9
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_10_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/10
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_11_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/11
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_13_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/13
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_14_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/14
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_15_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/15
# python parse_haplotype_catalog.py /u/project/ngarud/Garud_lab/UHGG/haplotypes/Bacteroides_eggerthii/GUT_GENOME095991_16_haplotypes.csv /u/project/ngarud/Garud_lab/UHGG/distances/dendrograms/manual_clade_definitions.txt Bacteroides_eggerthii ../Data/UHGG/UHGG_Bacteroides_eggerthii/16
